server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    # 是否从其他eureka server节点获取服务信息，单机模式下设为false
    fetch-registry: false
    # 是否注册到其他eureka server节点，单机模式下设为false
    register-with-eureka: false